#!/bin/bash

# apt install fonts-font-awesome

# # Check mouse event
# case $BLOCK_BUTTON in
#     3)
#     #/usr/bin/amixer set Capture toggle &>/dev/null;  # AlsaMixer
#     /usr/bin/pactl set-source-mute 1 toggle;  # PulseAudio
# esac


# Determine mic's state
#amixer contents | grep -q "values=off" && [[ $? -eq 0 ]] && state="off";  # If you use AlaMixer
pactl list sources | grep -q "Mute: yes" && [[ $? -eq 0 ]] && state="off";  # If you rather go with PulseAudio


# Toggle mic's state
case $state in
    off)
    echo "  " " muted ";
    #echo "  "
    echo
    echo \#005FD7;  # Soft blue
    #echo \#00FF00;  # Bright green
    exit 0;
    ;;
    *)
    echo "     " " OPEN   ";
    #echo "      ";
    exit 33;
    ;;
esac

exit 0;
