#!/usr/bin/env bash

EXITCODE=0
FILES=`git diff --cached --name-only | grep -E '\.rb(\..+)?$'`
for FILE in $FILES ; do
  GREP_COLOR='4;31' grep --color --with-filename --line-number --context=2 'binding.pry' $FILE
  if [ $? -eq 0 ]; then
    EXITCODE=1
  fi
done

if [ $EXITCODE -gt 0 ]; then
  echo
  echo "Aborted by pre-commit (override with --no-validate)."
fi

exit $EXITCODE

