#!/bin/bash

# apt install fonts-font-awesome

pactl get-source-mute @DEFAULT_SOURCE@ | grep -q "Mute: yes" && [[ $? -eq 0 ]] && state="off";


case $state in
    off)
    echo "  ";
    exit 0;
    ;;
    *)
    echo "     " " OPEN   ";
    exit 33;
    ;;
esac

exit 0;
